weekly_playlist = ["Blinding Lights","Levitating","As It Was","Heat Waves","Good 4 u"]
weekly_playlist.append("Drivers License")
weekly_playlist.insert(0,"Bohemian Rhapsody")
weekly_playlist.remove("Good 4 u")
print("The song \"Levitating\" is on index:",weekly_playlist.index("Levitating"))
print("There are/is",weekly_playlist.count("As It Was"),"song my Harry Styles")
throwback_thursday = weekly_playlist.copy()
throwback_thursday.reverse()
print("Throwback Thursday playlist =",throwback_thursday)
weekly_playlist.sort()
print("The final version of the playlist is:",weekly_playlist)
print("The number of songs in the playlist is:",len(weekly_playlist))